k9s:
  cluster: kind-kind-cluster
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: kubernetes.m.crossplane.io/v1alpha1/objects all
  featureGates:
    nodeShell: false
  proxy: null
