k9s:
  cluster: kind-kind-cluster
  namespace:
    active: maglev-dev
    lockFavorites: false
    favorites:
      - maglev-dev
      - all
      - default
      - maglev-api
      - maglev
  view:
    active: v1/pods
  featureGates:
    nodeShell: false
  proxy: null
