k9s:
  cluster: kind-kind-cluster
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
