k9s:
  cluster: AKS20LOCO100-P
  namespace:
    active: ns20rrp100-p
    lockFavorites: false
    favorites:
      - ns20rrp100-p
      - maglev-privateagent
      - all
      - ns20mcm100-p
      - ns20ccmportal100-p
      - ns20svfres100-p
      - kube-system
      - maglev-operations
      - maglev-operator
  view:
    active: pod ns20rrp100-p
  featureGates:
    nodeShell: false
  proxy: null
