k9s:
  cluster: AKS20LOCO100-P
  namespace:
    active: maglev-monitoring
    lockFavorites: false
    favorites:
      - ns20mk100-p
      - ns20sw100-p
      - ns20locot100-p
      - ns20baas100-p
      - ns20loco100-p
      - default
      - maglev-operations
      - maglev-monitoring
      - ns20rw100-p
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
