k9s:
  cluster: AKS20LOCO100-P
  namespace:
    active: maglev-privateagent
    lockFavorites: false
    favorites:
      - maglev-privateagent
      - ns20obf100-p
      - ns20ccmportal100-p
      - ns20mk100-p
      - ns20sw100-p
      - ns20locot100-p
      - ns20baas100-p
      - ns20loco100-p
      - default
  view:
    active: v1/pods maglev-privateagent
  featureGates:
    nodeShell: false
  proxy: null
