k9s:
  cluster: AKS20CCMMAGLV100-DEV
  namespace:
    active: backstage
    lockFavorites: false
    favorites:
      - all
      - backstage
      - default
      - ns20loco100-ta
  view:
    active: v1/pods
  featureGates:
    nodeShell: false
  proxy: null
