k9s:
  cluster: AKS20CCMMAGLV100-DEV
  namespace:
    active: ns20loco100-ta
    lockFavorites: false
    favorites:
      - ns20loco100-ta
      - all
      - backstage
      - default
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
