k9s:
  cluster: AKS40LOCO100-P
  namespace:
    active: nsco-agic
    lockFavorites: false
    favorites:
      - ns40loco100-p
      - nsco-agic
      - nsco-monitoring
      - default
  view:
    active: cm
  featureGates:
    nodeShell: false
  proxy: null
