k9s:
  cluster: aks-sovereign-service
  namespace:
    active: backstage
    lockFavorites: false
    favorites:
      - app-routing-system
      - argocd
      - cert-manager
      - backstage
      - default
  view:
    active: v1/pods backstage
  featureGates:
    nodeShell: false
  proxy: null
