k9s:
  cluster: AKS20LOCO100-TA
  namespace:
    active: ns20rails100-ta
    lockFavorites: false
    favorites:
      - ns20rails100-ta
      - all
      - kube-system
      - ns20ccmportal100-ta
      - ns20loco100-ta
      - maglev-operations
      - maglev-monitoring
      - ns20spot100-ta
      - nsco-monitoring
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
