k9s:
  cluster: AKS20LOCO100-TA
  namespace:
    active: ns20mcm100-ta
    lockFavorites: false
    favorites:
      - ns20hijr100-ta
      - maglev-privateagent
      - ns20loco100-ta
      - ns20spel100-ta
      - ns20bamash100-ta
      - all
      - ns20mcm100-ta
      - ns20locot100-ta
      - ns20svfres100-ta
  view:
    active: mendixapp
  featureGates:
    nodeShell: false
  proxy: null
