k9s:
  cluster: AKS20LOCO100-TA
  namespace:
    active: maglev-api
    lockFavorites: false
    favorites:
      - maglev-privateagent
      - maglev-api
      - ns20rails100-ta
      - all
      - kube-system
      - ns20ccmportal100-ta
      - ns20loco100-ta
      - maglev-operations
      - maglev-monitoring
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
