k9s:
  cluster: AKS20LOCO100-TA
  namespace:
    active: maglev-privateagent
    lockFavorites: false
    favorites:
      - maglev-monitoring
      - ns20spot100-ta
      - nsco-monitoring
      - maglev-operator
      - ns20pret100-ta
      - all
      - maglev-privateagent
      - ns20ora100-ta
      - ns20loco100-ta
  view:
    active: v1/pods maglev-privateagent
  featureGates:
    nodeShell: false
  proxy: null
